version: "3"

services:
  quart_server:
    container_name: quart_server
    build: quart_app/
    restart: always
    command: hypercorn -b 0.0.0.0:5000 ./quart_app:app
    # hypercorn is ASGI server for deploy
    links:
      - mysql:mysql
    volumes:
      - ./quart_app:/usr/src/quart_app:ro
      - ./storage/private:/quart_database/private
    environment:
      MYSQL_ROOT_PASSWORD: root

  nginx:
    image: nginx:1.18-alpine
    container_name: nginx
    restart: always
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-logs:/var/log/nginx
      - ./storage/static-data:/usr/share/nginx/html:ro
      # :ro means read-only
    links:
      - quart_server
    command: [nginx, '-g', 'daemon off;']
    # daemon off because docker is already works in daemon mode

  mysql:
    image: mysql:8
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users_db

  # adminer:
  #     image: adminer
  #     restart: always
  #     ports:
  #       - 8091:8091
